Gaming Tournament Site
Chimwemwe-127001/module_1_capstone pull request #1
Opened 2021-10-12 22:18 UTC by Chimwemwe-127001

## Gaming Tournament Site
In this website update, the following requirements have been implemented:
- [x] Personalize page content.
- [x] Follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- [x] Pages should look almost identical to the original design. Room for small adjuments, allowed.
- [x] Build Home page and About page.
- [x] Page versions (Mobile: up to 768px wide.) (Desktop: 768px or wider.)
- [x]  Interactions:
## Links
> The home page should have a link in the menu to the about page.
> The logo in the header links to the home page.
> Mobile menu
> When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
> There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
>  The mobile menu should have a close (X) button that closes the menu.
- [x] Dynamic

2021-10-12 23:12 UTC, carlos-ssh requested changes
Hi @Chimwemwe-127001 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![changesrequested](https://user-images.githubusercontent.com/22258274/137041083-6d095d86-729f-4f97-be48-1384d63ec4dc.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 23:12 UTC, carlos-ssh commented on README.md
- Provide a video link with maximum length of the video is 5 minutes in professional English
- the video should contains a demo of the project, showing the pages in different screen sizes and 
- the video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2021-10-13 06:20 UTC, Chimwemwe-127001 commented on README.md
Thank you very much @carlos-ssh for the review. I have made the required changes as requested. Hopefully, my second attempt will be approved.
Happy Coding!!😁👨‍💻

2021-10-13 06:31 UTC, henatan99 commented on README.md
This issue is well addressed. Thank you for making the requested changes. :clap: :+1:

2021-10-13 06:40 UTC, henatan99 approved these changes
Hi @Chimwemwe-127001, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-13 06:40 UTC, henatan99 commented on style.css
> +}
- [ ] OPTIONAL: Personalizing is meant for the contents only not the design requirements. You should always consider design requirements as the client's business requirements and you should make your design as close as the original design. It includes the background color, typography (color, font style, font-family, font-size), spacing, positioning, color and size contrast, etc... Kindly look at the attached screenshot below just as a reference and take a lesson for your future work. :pray: 

![image](https://user-images.githubusercontent.com/64894927/137080276-31a387cb-720e-44b8-9d9f-5f1a97e276bc.png)
![image](https://user-images.githubusercontent.com/64894927/137080317-71c7a99c-393a-4b0a-a78e-5171a7231cea.png)

2021-10-13 06:41 UTC, Chimwemwe-127001 commented on README.md
> Thank you very much @henatan99, for addressing the issue...👍

2021-10-13 06:54 UTC, Chimwemwe-127001 commented on style.css
> +}
- Thank you a lot for this insightful review 🤓 . I am currently working to ensure this is rectified. This has really helped me take a deep understanding of clients' business requirements. I will surely take this lesson for my future work.
- Thank you once more for the review. 
HAPPY CODING!!!😁👨‍💻👨‍💻

2021-10-13 06:54 UTC, merged